library strings;

const String API_EXPO = "https://festiwalnauki.edu.pl/fn-rest/wystawy-aplikacja.json";
const String API_MEETINGS = "https://festiwalnauki.edu.pl/fn-rest/spotkania-aplikacja.json";
const String API_LECTURES = "https://festiwalnauki.edu.pl/fn-rest/lekcje-aplikacja.json";
const String GOOGLE_API_KEY = "AIzaSyBwvapxyHvVcWErtmF_JsJN_dOn4UA36wo";
const String THOROUGHFARE = "Adres";
const String DATE = "Data";
const String ADDITIONAL_INFO = "Dodatkowe Informacje";
const String MAP = "Mapa";
const String SIGN_UP = "Zapisz się";
const String YOUR_EVENTS = "Twoje wydarzenia";
const String ERROR_MESSAGE = "Coś poszło nie tak...";
const String MEETINGS = "Spotkania";
const String LESSONS = "Lekcje";
const String LECTURES = "Wykłady";
const String SEARCH = "Wyszukaj";
const String LOG_IN_MESSAGE = "Logowanie...";
const String LOGIN_ERROR = "Logowanie się nie powiodło";
const String LOG_IN = "Zaloguj się";
const String EMAIL = "Email";
const String EMAIL_HINT = "Wpisz swój email";
const String PASSWORD = "Hasło";
const String PASSWORD_HINT = "Wpisz swoje hasło";
const String NEW_ACCOUNT = "Nie masz konta? Zarejestruj się!";
const String NO_DATA = "Brak danych";
